### ISSUE TITLE
Linux automatic version crash on upload

### ISSUE THREAD

**Issue by Erikvv** [Cairath/tools-not-included#19]
**Describe the bug**
After map generation is finished the "Begin" modal shows up and the game crashes

**Expected behavior**
ONI version: Q3-336724
Mod version: 1.0.0.0
Last log entry: (~/.config/unity3d/Klei/Oxygen Not Included/Player.log)
```
Receiving unhandled NULL exception
#0  0x007ffc58827ac0 in funlockfile
#1  0x007ffc58828158 in operator new[](unsigned long, std::nothrow_t const&)
#2  0x007ffc58828168 in operator new[](unsigned long, std::nothrow_t const&)
#3  0x007ffc58828188 in char* std::string::_S_construct<char*>(char*, char*, std::allocator<char> const&, std::forward_iterator_tag)
#4  0x007ffc588281a8 in __gnu_cxx::new_allocator<std::tr1::__detail::_Hash_node<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*>, false>*>::deallocate(std::tr1::__detail::_Hash_node<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*>, false>**, unsigned long)
#5  0x007ffc588281d8 in std::tr1::_Hashtable<std::pair<google::protobuf::EnumDescriptor const*, int>, std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*>, std::allocator<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*> >, std::_Select1st<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*> >, std::equal_to<std::pair<google::protobuf::EnumDescriptor const*, int> >, google::protobuf::(anonymous namespace)::PointerIntegerPairHash<std::pair<google::protobuf::EnumDescriptor const*, int> >, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::_M_deallocate_buckets(std::tr1::__detail::_Hash_node<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*>, false>**, unsigned long)
#6  0x007ffc58828228 in std::tr1::_Hashtable<std::pair<google::protobuf::EnumDescriptor const*, int>, std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*>, std::allocator<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*> >, std::_Select1st<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*> >, std::equal_to<std::pair<google::protobuf::EnumDescriptor const*, int> >, google::protobuf::(anonymous namespace)::PointerIntegerPairHash<std::pair<google::protobuf::EnumDescriptor const*, int> >, std::tr1::__detail::_Mod_range_hashing, std::tr1::__detail::_Default_ranged_hash, std::tr1::__detail::_Prime_rehash_policy, false, false, true>::~_Hashtable()
#7  0x007ffc58828258 in std::tr1::__unordered_map<std::pair<google::protobuf::EnumDescriptor const*, int>, google::protobuf::EnumValueDescriptor const*, google::protobuf::(anonymous namespace)::PointerIntegerPairHash<std::pair<google::protobuf::EnumDescriptor const*, int> >, std::equal_to<std::pair<google::protobuf::EnumDescriptor const*, int> >, std::allocator<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*> >, false>::~__unordered_map()
#8  0x007ffc58828278 in std::tr1::unordered_map<std::pair<google::protobuf::EnumDescriptor const*, int>, google::protobuf::EnumValueDescriptor const*, google::protobuf::(anonymous namespace)::PointerIntegerPairHash<std::pair<google::protobuf::EnumDescriptor const*, int> >, std::equal_to<std::pair<google::protobuf::EnumDescriptor const*, int> >, std::allocator<std::pair<std::pair<google::protobuf::EnumDescriptor const*, int> const, google::protobuf::EnumValueDescriptor const*> > >::~unordered_map()
#9  0x007ffc58828298 in google::protobuf::hash_map<std::pair<google::protobuf::EnumDescriptor const*, int>, google::protobuf::EnumValueDescriptor const*, google::protobuf::(anonymous namespace)::PointerIntegerPairHash<std::pair<google::protobuf::EnumDescriptor const*, int> >, std::equal_to<std::pair<google::protobuf::EnumDescriptor const*, int> > >::~hash_map()
#10 0x007ffc588282b8 in google::protobuf::FileDescriptorTables::~FileDescriptorTables()
#11 0x007ffc588282d8 in __run_exit_handlers
#12 0x007ffc58828328 in exit
#13 0x007ffc58828338 in mono_thread_exit
#14 0x007ffc58828348 in mono_print_thread_dump
#15 0x007ffc58828608 in mono_amd64_throw_exception
#16 0x007ffc588287c8 in (Unknown)
#17 0x007ffc588287d8 in (Unknown)
#18 0x007ffc588287e8 in mono_set_defaults
#19 0x007ffc58828b80 in mono_runtime_invoke
#20 0x007ffc58828bb0 in operator new[](unsigned long, std::nothrow_t const&)
#21 0x007ffc58828be0 in operator new[](unsigned long, std::nothrow_t const&)
#22 0x007ffc58828c00 in operator new[](unsigned long, std::nothrow_t const&)
#23 0x007ffc58828f30 in operator new[](unsigned long, std::nothrow_t const&)
#24 0x007ffc58828f70 in operator new[](unsigned long, std::nothrow_t const&)
#25 0x007ffc58828f80 in operator new[](unsigned long, std::nothrow_t const&)
#26 0x007ffc58828fe0 in operator new[](unsigned long, std::nothrow_t const&)
#27 0x007ffc58829150 in operator new[](unsigned long, std::nothrow_t const&)
#28 0x007ffc588292c0 in operator new[](unsigned long, std::nothrow_t const&)
#29 0x007ffc58829340 in oc_frag_recon_inter2_c
#30 0x007ffc58829930 in __libc_start_main
#31 0x007ffc588299f0 in oc_frag_recon_inter2_c
```

**Comment by Erikvv** [comment]
After trying again I get the same stack trace as https://github.com/Cairath/tools-not-included/issues/18 so it is probably the same issue.

**Comment by loscil06** [comment]
On a related note: is it possible to install this mod in Linux? I'm using ubuntu 19.04 following the instructions that are in the main website. I put the modloader in ~/.steam/steam/steamapps/common/OxygenNotIncluded/OxygenNotIncluded_Data and the mod in /.steam/steam/steamapps/common/OxygenNotIncluded/Mods and doesn't seem to be working. When in game, it's doesn't look like it's detecting the mod. 
I want to contribute by uploading seeds. I tried searching install instructions for Linux to no avail (both here and in the klei forums, all mentions about Linux is that seeds are the same).

**Comment by Erikvv** [comment]
@loscil06 The modloader file needs to be ~/.steam/steam/steamapps/common/OxygenNotIncluded/OxygenNotIncluded_Data/Managed/ModLoader.dll

It does load for me using the paths you describe.

**Comment by loscil06** [comment]
@Erikvv Mine has something that the modloader crashed, here's the gist for more info: https://gist.github.com/loscil06/ab364e3b13e72f43dbc8c0be1963b5cd
Though mine still doesn't detect the mod in-game.
